In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from typing import List, Tuple, Dict
from collections.abc import Iterable
from functools import total_ordering
import operator as op
from datetime import date

## Basics types

In [2]:
d = 3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333339
d

3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333339

In [3]:
type(d)

int

In [4]:
# numpy proposes numeric types with size
# uint8, uint16, uint32, uint64, int8, int16, int32, int64,
# float32, float64
m = np.zeros((1000,1000),dtype='uint8')
m

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [5]:
m2 = np.ones((1000,1000), dtype=np.float32)
m2

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

## Algorithm for executing operators

In [6]:
m3 = np.random.normal(10.0, 4.5, (1000,1000))
m3

array([[ 8.44819172,  6.01320313, 13.02818864, ..., 15.16895682,
        12.44671144, 14.97809733],
       [11.04917355, 15.07022509, 15.75034368, ..., 10.17705782,
        15.93775993, 13.67121288],
       [20.38565353,  5.52152683, 10.48625315, ...,  4.09554192,
         8.27574195,  9.10410313],
       ...,
       [ 4.54924462,  9.35137091,  6.86167136, ...,  7.65583746,
         4.97040358, 11.58878766],
       [ 7.9857869 , 10.56824099,  7.98309447, ..., 10.60391573,
        12.1901986 , 12.77961055],
       [ 8.07939407, 13.83406299, 14.4762475 , ...,  5.36194606,
         8.45789325, 11.11986607]])

In [7]:
# produit matriciel
res = m2 @ m3
print(type(res))
res

<class 'numpy.ndarray'>


array([[10144.67088676, 10261.33947387, 10116.32722027, ...,
        10124.54778999, 10240.27235656, 10039.15492019],
       [10144.67088676, 10261.33947387, 10116.32722027, ...,
        10124.54778999, 10240.27235656, 10039.15492019],
       [10144.67088676, 10261.33947387, 10116.32722027, ...,
        10124.54778999, 10240.27235656, 10039.15492019],
       ...,
       [10144.67088676, 10261.33947387, 10116.32722027, ...,
        10124.54778999, 10240.27235656, 10039.15492019],
       [10144.67088676, 10261.33947387, 10116.32722027, ...,
        10124.54778999, 10240.27235656, 10039.15492019],
       [10144.67088676, 10261.33947387, 10116.32722027, ...,
        10124.54778999, 10240.27235656, 10039.15492019]])

In [8]:
# element wise
m2 * m3

array([[ 8.44819172,  6.01320313, 13.02818864, ..., 15.16895682,
        12.44671144, 14.97809733],
       [11.04917355, 15.07022509, 15.75034368, ..., 10.17705782,
        15.93775993, 13.67121288],
       [20.38565353,  5.52152683, 10.48625315, ...,  4.09554192,
         8.27574195,  9.10410313],
       ...,
       [ 4.54924462,  9.35137091,  6.86167136, ...,  7.65583746,
         4.97040358, 11.58878766],
       [ 7.9857869 , 10.56824099,  7.98309447, ..., 10.60391573,
        12.1901986 , 12.77961055],
       [ 8.07939407, 13.83406299, 14.4762475 , ...,  5.36194606,
         8.45789325, 11.11986607]])

In [9]:
# __mul__ du type int
4 * 3

12

In [10]:
# __mul__ du type int: NotImplemented
# __rmul__ du type float
4 * 2.3

9.2

In [11]:
# type str
print("ah" * 3)
print(3 * "ah")

ahahah
ahahah


In [12]:
# str and int: NotImplemented
try:
    res = "ah" + 3
except TypeError as e:
    # TypeError: can only concatenate str (not "int") to str
    print("ça marche pas", type(e), e, sep=" -> ")
    print(f"ça marche pas: {type(e)}; message: {e}")

ça marche pas -> <class 'TypeError'> -> can only concatenate str (not "int") to str
ça marche pas: <class 'TypeError'>; message: can only concatenate str (not "int") to str


In [13]:
d = date.today()
n = 1 / 3
print(d,n)
print(f"today: {d:%d/%m/%Y}, pression: {n:0.3f}")  # python 3.6
print("today: {0:%d/%m/%Y}, pression: {1:0.3f}".format(d,n)) # python 3
print("today: %s, pression: %s" % (d,n)) # old python

2022-10-07 0.3333333333333333
today: 07/10/2022, pression: 0.333
today: 07/10/2022, pression: 0.333
today: 2022-10-07, pression: 0.3333333333333333


In [14]:
# div entiere (Euclide)
11 // 3, 11 % 3, 11 / 3, divmod(11,3) 

(3, 2, 3.6666666666666665, (3, 2))

In [15]:
# str : end-user
print(str(m3))
# repr: dev, python interactif
print(repr(m3))

[[ 8.44819172  6.01320313 13.02818864 ... 15.16895682 12.44671144
  14.97809733]
 [11.04917355 15.07022509 15.75034368 ... 10.17705782 15.93775993
  13.67121288]
 [20.38565353  5.52152683 10.48625315 ...  4.09554192  8.27574195
   9.10410313]
 ...
 [ 4.54924462  9.35137091  6.86167136 ...  7.65583746  4.97040358
  11.58878766]
 [ 7.9857869  10.56824099  7.98309447 ... 10.60391573 12.1901986
  12.77961055]
 [ 8.07939407 13.83406299 14.4762475  ...  5.36194606  8.45789325
  11.11986607]]
array([[ 8.44819172,  6.01320313, 13.02818864, ..., 15.16895682,
        12.44671144, 14.97809733],
       [11.04917355, 15.07022509, 15.75034368, ..., 10.17705782,
        15.93775993, 13.67121288],
       [20.38565353,  5.52152683, 10.48625315, ...,  4.09554192,
         8.27574195,  9.10410313],
       ...,
       [ 4.54924462,  9.35137091,  6.86167136, ...,  7.65583746,
         4.97040358, 11.58878766],
       [ 7.9857869 , 10.56824099,  7.98309447, ..., 10.60391573,
        12.1901986 , 12.77961055

In [16]:
m.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [17]:
# numpy protects its attributes
# del m.flags
# AttributeError: attribute 'flags' of 'numpy.ndarray' objects is not writable

In [18]:
m.T.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [19]:
# del m.shape # AttributeError: Cannot delete array shape
# write is possible if compatible (shape is a property with validation)
m.shape = (100,10000) # => reshape

# ValueError: cannot reshape array of size 1000000 into shape (10000,10000)
# m.shape = (10000, 10000) 

## Pandas dataframes

In [20]:
df = pd.read_excel('data.xlsx', sheet_name='Janvier')
df

Date       Nom  Mesure
0 2022-10-05       Pau     3.3
1 2022-07-08  Toulouse     2.6

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    2 non-null      datetime64[ns]
 1   Nom     2 non-null      object        
 2   Mesure  2 non-null      float64       
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 176.0+ bytes


In [22]:
oneDate = df.loc[0,'Date']
type(oneDate)

pandas._libs.tslibs.timestamps.Timestamp

In [23]:
oneCity = df.loc[0,'Nom']
type(oneCity)

str

In [24]:
df[df.Nom.str.startswith('T')]

Date       Nom  Mesure
1 2022-07-08  Toulouse     2.6

In [25]:
df[df.Date.dt.year == 2022]

Date       Nom  Mesure
0 2022-10-05       Pau     3.3
1 2022-07-08  Toulouse     2.6

In [26]:
isinstance(df,object), isinstance(df,pd.DataFrame)

(True, True)

In [27]:
dir(df)

['Date',
 'Mesure',
 'Nom',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__

In [28]:
len(df)

2

In [29]:
# len(4)
# dir(int)

In [30]:
len([1,3, 44])
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [31]:
# list comprehension
[ f for f in dir(df) if 'repr' in f ]

['__repr__',
 '_info_repr',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_']

In [32]:
for f in dir(df):
    if 'repr' in f:
        print(f)

__repr__
_info_repr
_repr_data_resource_
_repr_fits_horizontal_
_repr_fits_vertical_
_repr_html_
_repr_latex_


In [33]:
g = (f for f in dir(df) if 'repr' in f)
g

<generator object <genexpr> at 0x000001FE1523FB30>

In [34]:
",".join(g)

'__repr__,_info_repr,_repr_data_resource_,_repr_fits_horizontal_,_repr_fits_vertical_,_repr_html_,_repr_latex_'

In [35]:
",".join(g) # generator already consumed

''

In [36]:
",".join(f for f in dir(df) if 'repr' in f)

'__repr__,_info_repr,_repr_data_resource_,_repr_fits_horizontal_,_repr_fits_vertical_,_repr_html_,_repr_latex_'

In [37]:
values = [3, 5, 9]

In [38]:
[ v**2+1 for v in values ]

[10, 26, 82]

In [39]:
# only parameter, no extra parenthesis
sum(v**2+1 for v in values)

118

In [40]:
# 2 parameters => generator expr must be parenthesized
sum((v**2+1 for v in values), 100)

218

In [41]:
# lazy object ~ generator
range(100)

range(0, 100)

In [42]:
def genFibo():
    """ infinite generator, Fibonaci suite """
    a = 0
    b = 1
    yield a
    yield b
    while True:
        a, b = b, a+b
        yield b
    

In [43]:
g = genFibo()
g

<generator object genFibo at 0x000001FE152AA0B0>

In [44]:
for _ in range(10):
    print(next(g))

0
1
1
2
3
5
8
13
21
34


In [45]:
_

9

In [46]:
listFibo = list(zip(range(10), genFibo()))
listFibo

[(0, 0),
 (1, 1),
 (2, 1),
 (3, 2),
 (4, 3),
 (5, 5),
 (6, 8),
 (7, 13),
 (8, 21),
 (9, 34)]

All is connected:
- iterable: __iter__, iter()
- iterator: __next__, is iterable (self)
- generator

In [47]:
dir(genFibo) # a function is callable => '__call__'

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [48]:
it = iter(listFibo)

In [49]:
# until exception StopIteration
next(it)

(0, 0)

In [50]:
assert iter(it) is it

In [51]:
%timeit l = list(zip(range(10000), genFibo()))

7.24 ms ± 1.48 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
%time l = list(zip(range(10000), genFibo()))

Wall time: 11.8 ms


# Sequences and Dictionaries

In [53]:
# sequence : list, tuple, set
# villes: list => no constraint on elements
villes: List[str] = [ "Toulouse", 'Pau', "Bayonne" ]  # list, dynamic size, "homogene"
tupleVille = ("Toulouse", 471941, 31000) # tuple, fixed size, "heterogene"
cartes = { 'AS', 'ROI', '11' } # set


In [54]:
# use linter, type checker to forbid following lines
villes.append(1)
villes

['Toulouse', 'Pau', 'Bayonne', 1]

In [55]:
cartes.add('AS')
cartes

{'11', 'AS', 'ROI'}

In [56]:
# dictionnaries: dynamique
dictVille = { "name":"Toulouse", "pop":471941, "cp":31000 }

In [57]:
dictVille["mayor"] = "John Doe"
dictVille

{'name': 'Toulouse', 'pop': 471941, 'cp': 31000, 'mayor': 'John Doe'}

In [58]:
del dictVille["mayor"]
dictVille

{'name': 'Toulouse', 'pop': 471941, 'cp': 31000}

In [59]:
del villes[3]
villes

['Toulouse', 'Pau', 'Bayonne']

In [60]:
x = None
type(x), x is None, x is not None

(NoneType, True, False)

In [61]:
villes == [ "Toulouse", 'Pau', "Bayonne" ]

True

In [62]:
villes is [ "Toulouse", 'Pau', "Bayonne" ]

False

In [63]:
villes[0] is "Toulouse"

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Matthias\AppData\Local\Temp\ipykernel_13240\3747428822.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  villes[0] is "Toulouse"


True

In [64]:
# interfaces collections.abc (UML/Java like)
isinstance(villes, Iterable)

True

In [65]:
type(villes) is list

True

## Simple Class

In [66]:
#class Movie(object):
@total_ordering
class Movie:
    
    # to protect attribute list
    __slots__ = ['title', 'year']
    
    # constructor
    def __init__(self, title=None, year=None):
        self.title = title
        self.year = year
        
    # __repr__ => ____str__
    def __repr__(self):
        return f"{self.title} ({self.year})"
    
    def __eq__(self, other):
        # strict typing (or isinstance)
        if type(other) != Movie:
            return NotImplemented
        return (self.title, self.year) == (other.title, other.year)
    
    def __hash__(self):
        # NB: None is False
        hash_title = hash(self.title) if self.title else 0
        hash_year = self.year if self.year is not None else 0
        return hash_title + hash_year
    
    def __lt__(self, other):
        if type(other) != Movie:
            return NotImplemented
        return (self.year, self.title) < (other.year, other.title)
    

        
    

In [67]:
movieDefault = Movie() # => __new__  puis __init__
movie = Movie('Top Gun: Maverick', 2022) 

In [68]:
print(movieDefault, movie)
movieDefault

None (None) Top Gun: Maverick (2022)


None (None)

In [69]:
movie.__repr__()

'Top Gun: Maverick (2022)'

In [70]:
Movie.__repr__(movie)

'Top Gun: Maverick (2022)'

In [71]:
dir(Movie)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 'title',
 'year']

In [72]:
movieDefault == movie 

False

In [73]:
movie == movie 

True

In [74]:
movie == Movie('Top Gun: Maverick', 2022)

True

In [75]:
# Movie, int: both return NotImplemented => False
movieDefault == 3

False

In [76]:
# ok by default, exception with __slots__
try:
    movie.duration = 123
    movie.duration
except AttributeError as e:
    print("With __slots__ not possible:", e)

With __slots__ not possible: 'Movie' object has no attribute 'duration'


In [77]:
del movie.duration

AttributeError: 'Movie' object has no attribute 'duration'

In [ ]:
# AttributeError: 'Movie' object has no attribute 'duration'
movie.duration

In [ ]:
movie.f = lambda x: movie.year + x 

In [ ]:
movie.f

In [ ]:
movie.f(3)

In [ ]:
movieDefault.f

In [ ]:
Movie.__init__

In [ ]:
movie2 = Movie("The Man Who Knew Too Much", 1956)
movie3 = Movie("The Man Who Knew Too Much", 1934)
movie4 = Movie("Prey", 2022)
movies = [ movie, movie2, movie3, movie4 ]

In [ ]:
movieSet = { movieDefault, movie, movie2, movie3, movie4 }
movieSet

In [ ]:
# dict comprehension
{ str(m): hash(m) for m in movieSet }

In [ ]:
movie2 < movie3, movie2 > movie3

In [ ]:
movie2 <= movie3

In [ ]:
# sort in place
movies.sort()
movies

In [ ]:
# tri dans une autre list
movies2 = sorted(m for m in movieSet if m.year is not None)
movies2

In [ ]:
movies.sort(reverse=True)
movies

In [ ]:
movies.sort(key = lambda m: m.title)  # m => m.title
movies

In [ ]:
movies.sort(key = lambda m: (m.title, m.year))
movies

In [ ]:
movies.sort(key = lambda m: (m.title, -m.year))
movies

In [ ]:
movies.sort(key = op.attrgetter('title'))  # m => m.title
movies

In [ ]:
op.attrgetter?

In [ ]:
class Person:
    pass

In [ ]:
p = Person()

In [ ]:
plt.plot?

In [ ]:
sum = lambda a,b: a-b

In [ ]:
# fake sum
sum(3,5)

In [ ]:
del sum

In [ ]:
# true builtin sum
sum((3,5))

In [ ]:
dir()

In [ ]:
# builtin sum is still there
__builtin__.sum

In [ ]:
# is, not are keywords
# is = sum
# SyntaxError: invalid syntax

## Time types in python and pandas

In [ ]:
from datetime import date, datetime, time, timedelta

In [ ]:
d = date.today()
dt = datetime.now()
print(d, dt, sep=" ; ")

In [ ]:
datetime.strptime("06/10/2022", "%d/%m/%Y").date()

In [ ]:
dFuture = datetime(2400, 2, 29)
dFuture

In [ ]:
dFuture + timedelta(days=3, hours=12)